#!/bin/bash
julia -i --depwarn=yes set_up.jl \
      --ExpName "LReLU" --model "LP" \
      --AE_widths 50 25 12 2 --AE_acts "relu" "relu" "id" \
      --Hom_widths 2 10 10 2 --Hom_acts "relu" "relu" "id" \
      --expansion_order 1 --spatial_scale 50 \
      --training_size 1000 --test_size 20 \
      --nEpochs 20 --nBatches 100 --nIterations 10 \
      --ADAMarg 0.001 \
      --P_DataFid 1.0 --P_Hom 1.0 --P_dx 1.0 --P_dz 1.0 \
      --tspan 0.0 0.1 --tsize 100 --z_dim 2 --mean_init 0.01 0.0


